import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import SheetProvider from "@/components/providers/sheet-provider";
import Footer from "@/components/footer";

const font = Alexandria({
  subsets: ["arabic"],
  weight: ["300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={font.className}>
        <SheetProvider />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
